name: Build and Release

on:
  push:
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-deb:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25.5'

    - name: Install golangci-lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.7.2
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Download dependencies
      run: go mod download

    - name: Run tests
      run: make test

    - name: Run linting
      run: make lint

    - name: Build Debian package
      run: make deb

    - name: Upload Debian package
      uses: actions/upload-artifact@v4
      with:
        name: libvirt-volume-provisioner-${{ github.ref_name }}-amd64.deb
        path: libvirt-volume-provisioner_0.1.0_amd64.deb

  build-and-push-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=tag
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  deploy-to-b2:
    needs: build-deb
    runs-on: ubuntu-latest
    environment: release

    steps:
    - name: Download Debian package
      uses: actions/download-artifact@v4
      with:
        name: libvirt-volume-provisioner-${{ github.ref_name }}-amd64.deb

    - name: Install MinIO Client
      run: |
        wget https://dl.min.io/client/mc/release/linux-amd64/mc
        chmod +x mc
        sudo mv mc /usr/local/bin/
        # Create mcli alias for consistency
        sudo ln -sf /usr/local/bin/mc /usr/local/bin/mcli

    - name: Configure B2
      run: |
        mcli alias set b2 https://s3.us-west-002.backblazeb2.com "$B2_KEY_ID" "$B2_APPLICATION_KEY"
      env:
        B2_KEY_ID: ${{ secrets.B2_KEY_ID }}
        B2_APPLICATION_KEY: ${{ secrets.B2_APPLICATION_KEY }}

    - name: Download existing repository
      run: |
        mkdir -p repo
        mcli cp --recursive b2/debs-golder-tech-static/ repo/

    - name: Add new package to repository
      run: |
        ./update-repo.sh libvirt-volume-provisioner_0.1.0_amd64.deb

    - name: Upload updated repository
      run: |
        cd repo
        mcli cp --recursive . b2/debs-golder-tech-static/

  create-release:
    needs: [build-deb, build-and-push-docker, deploy-to-b2]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download Debian package
      uses: actions/download-artifact@v4
      with:
        name: libvirt-volume-provisioner-${{ github.ref_name }}-amd64.deb

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: libvirt-volume-provisioner_0.1.0_amd64.deb
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
